# Covariance

* http://www.dummies.com/education/math/business-statistics/how-to-measure-the-covariance-and-correlation-of-data-samples/

In [68]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


In [2]:
data = np.array([[4.0, 4.2, 3.9, 4.3, 4.1], 
                 [2.0, 2.1, 2.0, 2.1, 2.2], 
                 [0.6, 0.59, 0.58, 0.62, 0.63]])

cov = np.cov(data)
print(cov.shape)
cov

(3, 3)


array([[ 0.025  ,  0.0075 ,  0.00175],
       [ 0.0075 ,  0.007  ,  0.00135],
       [ 0.00175,  0.00135,  0.00043]])

In [106]:
def covariance(data, ddof=0):
    k = data.shape[0]
    
    cov = np.zeros((k, k))
    for i in range(k):
        for j in range(k):
            a = data[i]
            b = data[j]
            cov[i, j] = np.sum((a-np.mean(a)) * (b-np.mean(b)))/(5-ddof)
    print(cov)
        
covariance(data, ddof=1)

[[ 0.025    0.0075   0.00175]
 [ 0.0075   0.007    0.00135]
 [ 0.00175  0.00135  0.00043]]


In [14]:
np.var(data, axis=1, ddof=1)

array([ 0.025  ,  0.007  ,  0.00043])

In [58]:
data2 = np.array([[90, 90, 60, 60, 30], 
                  [60, 90, 60, 60, 30], 
                  [90, 30, 60, 90, 30]])

print(np.cov(data2, ddof=0))
covariance(data2)

[[ 504.  360.  180.]
 [ 360.  360.    0.]
 [ 180.    0.  720.]]
[[ 24.   0.  30.]
 [ 24.  30. -30.]
 [ -6.   0.   0.]
 [ -6.   0.  30.]
 [-36. -30. -30.]]


In [87]:
import pandas as pd
d = pd.Series([1, 2, 1, 4, 2, 3, 1, 5])
d.diff(1)

0    NaN
1    1.0
2   -1.0
3    3.0
4   -2.0
5    1.0
6   -2.0
7    4.0
dtype: float64